package com.fragnostic.i18n

import java.util.{ Locale, ResourceBundle }

import com.fragnostic.i18n.api.ResourceI18n
import com.fragnostic.support.StringSupport

/**
 * Created by Fernando Brule on 30-06-2015 22:23:00.
 * Generated by Tesseract.
 */
private trait AbstractMultipleMessageI18n extends ResourceI18n with StringSupport {

  def getString(locale: Locale, key: String): String = {
    var mensaje = key
    var gotcha = false
    var idx = 0
    while (idx < getBundleNames.length && !gotcha) {
      val baseName = getBundleNames(idx)
      val bundle = ResourceBundle.getBundle(baseName, locale)
      if (bundle != null && bundle.containsKey(key)) {
        mensaje = bundle.getString(key)
        gotcha = true
      }

      idx = idx + 1
    }

    mensaje
  }

  def getFormattedString(
    locale: Locale,
    key: String,
    arguments: List[String]): String = {
    val mensaje = getString(locale, key)
    if (mensaje != null) {
      format(mensaje, arguments)
    } else {
      key
    }
  }

  def getBundleNames: List[String]

}

